name: JellyBook Android Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Workflow dependencies
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get
      - name: Build debug APK
        run: flutter build apk --debug
      - name: Build debug APK (split-per-abi)
        run: flutter build apk --debug --split-per-abi
      - name: Build debug App Bundle
        run: flutter build appbundle --debug
